import 'dart:convert';
import 'dart:ui' show Color;

import 'package:flutter/foundation.dart' show debugPrint;
import 'package:flutter/services.dart' show rootBundle;

import '../models/channel.dart';
import '../models/resource_category.dart';

/// Loads and indexes `assets/data/resource_categories.json` — the app-side
/// copy of FinReels' 60-category research (see resource_category.dart) —
/// AND every file under `assets/data/resources/`: one per category
/// (`{categoryId}.json`) plus `_general.json` for the 40 cross-cutting
/// channels/blogs/books that aren't tied to any single category.
///
/// One file per category on purpose — this is what "organized, not
/// complicated" means in practice: `assets/data/resources/` is a literal,
/// browsable checklist of the 60 categories. A file existing (and how
/// many of its 10/10/10 slots are filled) IS the progress tracker; no
/// separate spreadsheet needed. Each entry inside a file also carries a
/// `verifiedOn` + `verificationMethod` field — a permanent audit trail of
/// how it was actually checked, not just a claim made in chat once.
///
/// `resource_categories.json` (the research) is fully regenerated by
/// parse_curriculum.py any time the source docs change. The per-category
/// resource files are the opposite: never bulk-regenerated, only ever
/// grown one confirmed entry at a time.
///
/// Loaded once during startup (see main.dart's service-init group) so
/// that by the time any screen needs it, everything below is synchronous.
class ResourceCategoryData {
  ResourceCategoryData._();

  static List<ResourceCategory> _all = const [];
  static List<CurriculumModule> _modules = const [];
  static TaxReform? _taxReform;
  static bool _loaded = false;

  static bool get isLoaded => _loaded;
  static List<ResourceCategory> get all => _all;
  static List<CurriculumModule> get modules => _modules;
  static TaxReform? get taxReform => _taxReform;

  static final Map<String, ResourceCategory> _byId = {};

  static List<Channel> _verifiedChannels = const [];
  static List<Map<String, String>> _verifiedBlogs = const [];
  static List<VerifiedBook> _verifiedBooks = const [];
  static final Map<String, Map<String, dynamic>> _resourceFiles = {};

  static List<Channel> get verifiedChannels => _verifiedChannels;
  static List<Map<String, String>> get verifiedBlogs => _verifiedBlogs;
  static List<VerifiedBook> get verifiedBooks => _verifiedBooks;

  /// Idempotent — safe to call more than once (e.g. a screen calling it
  /// defensively); only the first call does real work.
  static Future<void> load() async {
    if (_loaded) return;
    try {
      final raw = await rootBundle.loadString('assets/data/resource_categories.json');
      final json = jsonDecode(raw) as Map<String, dynamic>;

      _modules = (json['modules'] as List)
          .map((m) => CurriculumModule.fromJson(m as Map<String, dynamic>))
          .toList(growable: false);

      _taxReform = TaxReform.fromJson(json['taxReform'] as Map<String, dynamic>);

      _all = (json['categories'] as List)
          .map((c) => ResourceCategory.fromJson(c as Map<String, dynamic>))
          .toList(growable: false);

      _byId
        ..clear()
        ..addEntries(_all.map((c) => MapEntry(c.id, c)));

      _loaded = true;
    } on Object catch (e) {
      // Never let a bad/missing asset take the app down — the picker and
      // the playbook books just degrade to "not available yet" instead.
      debugPrint('[ResourceCategoryData] categories load failed (non-fatal): $e');
    }

    // Separate try-catch from the categories load above — a failure here
    // (bad JSON in a single resource file, a null field, any parse error)
    // must NEVER leave _verifiedChannels/_verifiedBlogs/_verifiedBooks as
    // const [] for the whole session. Historically this call was outside the
    // try-catch above, which meant any exception inside _addFrom (e.g.
    // `null as String` on a book with a missing author field) propagated
    // uncaught through load(), was swallowed by _safeInit() in main.dart,
    // and left all three lists permanently empty — every channel shown was
    // general-only regardless of what the person had selected.
    try {
      await _loadVerifiedResources();
    } on Object catch (e) {
      debugPrint('[ResourceCategoryData] verified resources load failed (non-fatal): $e');
    }
  }

  static Future<void> _loadVerifiedResources() async {
    final channels = <Channel>[];
    final blogs = <Map<String, String>>[];
    final books = <VerifiedBook>[];

    // Every category's resource file, PLUS _general.json, read concurrently.
    // These are independent local asset reads with no ordering dependency
    // between them, so there's no reason to pay their latency one at a
    // time in a sequential await loop — that becomes real, user-visible
    // startup delay as more of the 60 categories get their own file (up to
    // 61 sequential awaits at full coverage). Future.wait runs them all at
    // once; total time becomes the slowest single read instead of the sum
    // of all of them. Each attempt is still fully independent — one
    // bad/missing file (most of these don't exist yet, and that's
    // expected, not an error — see _tryLoadResourceFile) never affects any
    // other, exactly as before.
    final results = await Future.wait([
      for (final category in _all)
        _tryLoadResourceFile('assets/data/resources/${category.id}.json'),
      _tryLoadResourceFile('assets/data/resources/_general.json'),
    ]);

    // _addFrom still runs in a fixed, deterministic order — category order,
    // then general last — regardless of which order the concurrent reads
    // above actually completed in, so the combined channel/blog/book lists
    // (and anything that depends on their order) stay stable across runs.
    for (var i = 0; i < _all.length; i++) {
      final map = results[i];
      if (map == null) continue;
      final category = _all[i];
      _resourceFiles[category.id] = map;
      _addFrom(map, category.id, channels, blogs, books);
    }

    // The general/cross-cutting resources — not tied to any category, so
    // resourceCategoryId stays null and they flow through
    // ChannelData.eagerFor() (and the equivalent scoping in
    // BlogRssService/FeedProvider) as always-on, exactly like the
    // original 12 channels.
    final general = results.last;
    if (general != null) {
      _resourceFiles['_general'] = general;
      _addFrom(general, null, channels, blogs, books);
    }

    _verifiedChannels = List.unmodifiable(channels);
    _verifiedBlogs = List.unmodifiable(blogs);
    _verifiedBooks = List.unmodifiable(books);
  }

  static Future<Map<String, dynamic>?> _tryLoadResourceFile(String path) async {
    try {
      final raw = await rootBundle.loadString(path);
      return jsonDecode(raw) as Map<String, dynamic>;
    } on Object {
      // Expected for the ~56 categories not started yet — not logged as
      // an error, this is the normal "not verified yet" state.
      return null;
    }
  }

  static void _addFrom(
    Map<String, dynamic> map,
    String? categoryId,
    List<Channel> channels,
    List<Map<String, String>> blogs,
    List<VerifiedBook> books,
  ) {
    for (final c in (map['channels'] as List? ?? [])) {
      try {
        final ch = c as Map<String, dynamic>;
        channels.add(Channel(
          id: ch['id'] as String,
          name: ch['name'] as String,
          handle: ch['handle'] as String,
          description: ch['description'] as String? ?? '',
          accentColor: Color(int.parse((ch['accentColor'] as String? ?? '0xFFF59E0B'))),
          category: 'Business of Your Skill',
          focus: ch['focus'] as String? ?? '',
          initials: ch['initials'] as String? ?? '',
          resourceCategoryId: categoryId,
        ));
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad channel entry '
            '(categoryId=$categoryId): $e');
      }
    }
    for (final b in (map['blogs'] as List? ?? [])) {
      try {
        final bl = b as Map<String, dynamic>;
        blogs.add({
          'name': bl['name'] as String,
          'url': bl['url'] as String,
          if (categoryId != null) 'categoryId': categoryId,
        });
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad blog entry '
            '(categoryId=$categoryId): $e');
      }
    }
    for (final bk in (map['books'] as List? ?? [])) {
      try {
        books.add(VerifiedBook.fromJson(bk as Map<String, dynamic>, categoryId: categoryId));
      } on Object catch (e) {
        debugPrint('[ResourceCategoryData] skipping bad book entry '
            '(categoryId=$categoryId): $e');
      }
    }
  }

  /// Raw parsed resource file for one category, e.g. to check "how many
  /// of the 10/10/10 slots are filled" for a progress display.
  static Map<String, dynamic>? verifiedFor(String categoryId) => _resourceFiles[categoryId];

  static ResourceCategory? byId(String id) => _byId[id];

  static List<ResourceCategory> bySection(ResourceSection section) =>
      _all.where((c) => c.section == section).toList(growable: false);

  static CurriculumModule? moduleByCode(String code) =>
      _modules.where((m) => m.code == code).firstOrNull;
}

extension _FirstOrNull<T> on Iterable<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
